### ISSUE TITLE
OgComplexWidget throws TypeError if editing user is not a member of group

### ISSUE THREAD

**Issue by xurizaemon** [Gizra/og#457]
When a user who is not a member of a OG Group tries to assign an OG Post to that group via the "Other groups" fields, Drupal throws an error 500. 

I tried to write a test for this and have not yet succeeded, so I figured I'd write up steps to reproduce.

* Install a fresh Drupal 8.6.x with OG enabled
* Log in as user "admin"
* Create content types Group (OG Group) and Post (OG Group Post)
* Create two new Groups, "Group A" + "Group B"
* Visit Group B and delete membership of user "admin"
* Create a new Post, "Post 1", and assign its audience to "Group A". Post saves fine.
* Edit the Post and using "Other Groups" assign it also to "Group B".
* Hitting save will throw an error 500.

The error message / backtrace is:

```
TypeError: Argument 1 passed to Drupal\Core\Field\Plugin\Field\FieldWidget\EntityReferenceAutocompleteWidget::errorElement() must be of the type array, null given, called in /vagrant/web/core/lib/Drupal/Core/Field/WidgetBase.php on line 455 in Drupal\Core\Field\Plugin\Field\FieldWidget\EntityReferenceAutocompleteWidget->errorElement() (line 120 of /vagrant/web/core/lib/Drupal/Core/Field/Plugin/Field/FieldWidget/EntityReferenceAutocompleteWidget.php)
#0 /vagrant/web/core/lib/Drupal/Core/Field/WidgetBase.php(455): Drupal\Core\Field\Plugin\Field\FieldWidget\EntityReferenceAutocompleteWidget->errorElement(NULL, Object(Symfony\Component\Validator\ConstraintViolation), Array, Object(Drupal\Core\Form\FormState)) 
#1 /vagrant/web/core/lib/Drupal/Core/Entity/Entity/EntityFormDisplay.php(258): Drupal\Core\Field\WidgetBase->flagErrors(Object(Drupal\Core\Field\EntityReferenceFieldItemList), Object(Symfony\Component\Validator\ConstraintViolationList), Array, Object(Drupal\Core\Form\FormState)) 
#2 /vagrant/web/core/lib/Drupal/Core/Entity/ContentEntityForm.php(272): Drupal\Core\Entity\Entity\EntityFormDisplay->flagWidgetsErrorsFromViolations(Object(Drupal\Core\Entity\EntityConstraintViolationList), Array, Object(Drupal\Core\Form\FormState)) 
#3 /vagrant/web/core/lib/Drupal/Core/Entity/ContentEntityForm.php(218): Drupal\Core\Entity\ContentEntityForm->flagViolations(Object(Drupal\Core\Entity\EntityConstraintViolationList), Array, Object(Drupal\Core\Form\FormState)) 
#4 [internal function]: Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object(Drupal\Core\Form\FormState)) 
#5 /vagrant/web/core/lib/Drupal/Core/Form/FormValidator.php(82): call_user_func_array(Array, Array) 
#6 /vagrant/web/core/lib/Drupal/Core/Form/FormValidator.php(275): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState)) 
#7 /vagrant/web/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'node_post_edit_...') 
#8 /vagrant/web/core/lib/Drupal/Core/Form/FormBuilder.php(575): Drupal\Core\Form\FormValidator->validateForm('node_post_edit_...', Array, Object(Drupal\Core\Form\FormState)) 
#9 /vagrant/web/core/lib/Drupal/Core/Form/FormBuilder.php(318): Drupal\Core\Form\FormBuilder->processForm('node_post_edit_...', Array, Object(Drupal\Core\Form\FormState)) 
#10 /vagrant/web/core/lib/Drupal/Core/Controller/FormController.php(93): Drupal\Core\Form\FormBuilder->buildForm('node_post_edit_...', Object(Drupal\Core\Form\FormState)) 
#11 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) 
#12 /vagrant/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) 
#13 /vagrant/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() 
#14 /vagrant/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) 
#15 /vagrant/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) 
#16 /vagrant/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() 
#17 /vagrant/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#18 /vagrant/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#19 /vagrant/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#20 /vagrant/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#21 /vagrant/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#22 /vagrant/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#23 /vagrant/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#24 /vagrant/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#25 /vagrant/web/core/lib/Drupal/Core/DrupalKernel.php(669): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#26 /vagrant/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#27 {main}.
```

**Comment by xurizaemon** [comment]
Huh, I see (#160, #181,  #412, #413) the widget may not be sticking around anyway. If so no need for this?

**Comment by amitaibu** [comment]
Yeah, we want to remove it completely in favor of Core's ER widgets.

Just need a brave soul to drive that PR home :)

**Comment by MPParsley** [comment]
OG complex widget will be removed in #181.
